version: '3'
services:
  cli:
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./docker/cli/Dockerfile
    volumes:
      - ./cli:/go/cli
    tty: true

  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    ports:
      - 5430:5432
    volumes:
      - db-store:/var/lib/postgresql/data
      - ./docker/db/init:/docker-entrypoint-initdb.d

  graphql:
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./docker/graphql/Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./graphql:/go/graphql
    tty: true
volumes:
  db-store:
