version: '3' # composeファイルのバージョン
services:
  app:
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes: # マウントディレクトリ
      - ./src:/go/src
    tty: true # コンテナの永続化
    # env_file: # .envファイル
    #   - ./build/.go_env
    environment:
      - TZ=Asia/Tokyo

  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    # image: postgres:16
    ports:
      - 5430:5432
    volumes:
      - db-store:/var/lib/postgresql/data
      - ./docker/db/init:/docker-entrypoint-initdb.d
    # environment:
    #   POSTGRES_USER: root
    #   POSTGRES_PASSWORD: passwd
volumes:
  db-store:
